name: release
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_SOURCE_DIR: ./src
  PROJECT_CONFIGURATION: Release
  PROJECT_ARTIFACTS_DIR: ./bin/Release/

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore src

    - name: Build
      run: dotnet build -c Release --no-restore src

    - name: Pack
      run: dotnet pack src/ImGui.NET -c Release --no-restore --no-build

    - name: Upload CodeGenerator
      uses: actions/upload-artifact@v3
      with:
        name: CodeGenerator
        path: ${{ env.PROJECT_ARTIFACTS_DIR }}/CodeGenerator/net7.0/

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: NuGet packages
        path: ${{ env.PROJECT_ARTIFACTS_DIR }}/ImGui.NET/*.nupkg

  publish:
    runs-on: windows-latest
    needs: build
    if: ${{ github.event.release.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Download CodeGenerator
        uses: actions/download-artifact@v3
        with:
          name: CodeGenerator
          path: ${{ env.PROJECT_ARTIFACTS_DIR }}/CodeGenerator/net7.0/

      - name: Validate Generated Code
        shell: bash
        run: |
          ${{ env.PROJECT_ARTIFACTS_DIR }}/CodeGenerator/net7.0/CodeGenerator.exe "src/ImGui.NET/Generated"
          git status -s | findstr . && echo "ERROR: CodeGenerator is not executed, please execute it." && exit 1 || exit 0

    # - name: Publish to nuget.org
    #   if: startsWith(github.ref, 'refs/tags/')
    #   run: dotnet nuget push bin\Release\ImGui.NET\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
